import type { Car, Testimonial, FAQItem } from "./types";

export const cars: Car[] = [
  {
    id: "1",
    name: "Volkswagen Golf",
    price: 40,
    transmission: "Manual",
    seats: 5,
    fuel: "Benzină",
    hasNoDeposit: true,
    category: "Sedan",
    gradientFrom: "#3b82f6",
    gradientTo: "#4f46e5",
  },
  {
    id: "2",
    name: "BMW 3 Series",
    price: 40,
    transmission: "Automat",
    seats: 5,
    fuel: "Benzină",
    category: "Sedan",
    gradientFrom: "#475569",
    gradientTo: "#1e3a5f",
  },
  {
    id: "3",
    name: "Mercedes-Benz E-Class",
    price: 55,
    transmission: "Automat",
    seats: 5,
    fuel: "Diesel",
    category: "Sedan",
    gradientFrom: "#374151",
    gradientTo: "#1f2937",
  },
  {
    id: "4",
    name: "Audi Q5",
    price: 31,
    transmission: "Automat",
    seats: 5,
    fuel: "Diesel",
    hasNoDeposit: true,
    category: "SUV",
    gradientFrom: "#10b981",
    gradientTo: "#047857",
  },
  {
    id: "5",
    name: "BMW X5",
    price: 40,
    transmission: "Automat",
    seats: 5,
    fuel: "Diesel",
    category: "SUV",
    gradientFrom: "#14b8a6",
    gradientTo: "#0d9488",
  },
  {
    id: "6",
    name: "Skoda Kodiaq",
    price: 78,
    transmission: "Automat",
    seats: 7,
    fuel: "Diesel",
    category: "SUV",
    gradientFrom: "#16a34a",
    gradientTo: "#15803d",
  },
  {
    id: "7",
    name: "Toyota RAV4",
    price: 23,
    transmission: "Manual",
    seats: 5,
    fuel: "Hibrid",
    hasNoDeposit: true,
    category: "SUV",
    gradientFrom: "#a3e635",
    gradientTo: "#16a34a",
  },
  {
    id: "8",
    name: "Porsche Cayenne",
    price: 78,
    transmission: "Automat",
    seats: 5,
    fuel: "Benzină",
    category: "SUV",
    gradientFrom: "#dc2626",
    gradientTo: "#991b1b",
  },
  {
    id: "9",
    name: "Volkswagen Polo",
    price: 25,
    transmission: "Manual",
    seats: 5,
    fuel: "Benzină",
    hasNoDeposit: true,
    category: "Hatchback",
    gradientFrom: "#fb923c",
    gradientTo: "#f97316",
  },
  {
    id: "10",
    name: "Audi A4",
    price: 35,
    transmission: "Automat",
    seats: 5,
    fuel: "Diesel",
    category: "Sedan",
    gradientFrom: "#6366f1",
    gradientTo: "#4338ca",
  },
  {
    id: "11",
    name: "Toyota Corolla",
    price: 28,
    transmission: "Manual",
    seats: 5,
    fuel: "Benzină",
    category: "Sedan",
    gradientFrom: "#38bdf8",
    gradientTo: "#0284c7",
  },
  {
    id: "12",
    name: "Honda Civic",
    price: 30,
    transmission: "Manual",
    seats: 5,
    fuel: "Benzină",
    category: "Sedan",
    gradientFrom: "#a78bfa",
    gradientTo: "#7c3aed",
  },
  {
    id: "13",
    name: "Renault Megane",
    price: 32,
    transmission: "Manual",
    seats: 5,
    fuel: "Diesel",
    category: "Hatchback",
    gradientFrom: "#facc15",
    gradientTo: "#d97706",
  },
  {
    id: "14",
    name: "Mazda CX-5",
    price: 38,
    transmission: "Automat",
    seats: 5,
    fuel: "Diesel",
    category: "SUV",
    gradientFrom: "#22d3ee",
    gradientTo: "#0891b2",
  },
  {
    id: "15",
    name: "Tesla Model 3",
    price: 65,
    transmission: "Automat",
    seats: 5,
    fuel: "Electric",
    category: "Sedan",
    gradientFrom: "#f43f5e",
    gradientTo: "#e11d48",
  },
  {
    id: "16",
    name: "Hyundai Tucson",
    price: 34,
    transmission: "Automat",
    seats: 5,
    fuel: "Hibrid",
    category: "SUV",
    gradientFrom: "#34d399",
    gradientTo: "#0d9488",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    title: "Mașini la cele mai bune prețuri",
    description:
      "Prețuri competitive și opțiuni diverse pentru orice buget și nevoie de deplasare.",
    author: "Alexandru M.",
    iconType: "price",
  },
  {
    id: "2",
    title: "Folosit și recomandat",
    description:
      "Serviciu profesional, mașini curate și în stare excelentă. Revenind cu plăcere.",
    author: "Maria T.",
    iconType: "star",
  },
  {
    id: "3",
    title: "Anonimitate garantată",
    description:
      "Procedura de închiriere este rapidă, simplă și asigură confidențialitatea datelor.",
    author: "Victor S.",
    iconType: "shield",
  },
  {
    id: "4",
    title: "Disponibil 24/7",
    description:
      "Suport client non-stop, livrare la adresa dumneavoastră oricând aveți nevoie.",
    author: "Elena R.",
    iconType: "clock",
  },
];

export const faqItems: FAQItem[] = [
  {
    id: "1",
    question:
      "Ce documente sunt necesare pentru a închirie un autoturism?",
    answer:
      "Avete nevoie de un permis de conducere valid (cel puțin 1 an), un act de identitate sau paport și o adresă de contact validă. Documentele vor fi verificate în momentul ridicării vehiculului.",
  },
  {
    id: "2",
    question:
      "Cu cât timp în advance trebuie să cer un autoturism?",
    answer:
      "Recomandam să faceți rezervarea cel puțin cu 24 de ore în avans pentru a asigura disponibilitatea modelului dorit. În perioadele de vârf, este recomandat cel puțin 48-72 de ore.",
  },
  {
    id: "3",
    question: "Ce este inclus în prețul de închiriere?",
    answer:
      "Prețul include asigurarea de răspundere civilă, kilometrii illimiti în Moldova și un nivel plein de combustibil. Asigurarea suplimentară și costurile de combustibil sunt separate.",
  },
  {
    id: "4",
    question: "Pot extinde perioada de închiriere?",
    answer:
      "Da, puteți extinde închirierea contactând echipa noastră cel puțin cu 24 de ore înainte de data planificată de retur, sub rezerva disponibilității vehiculului.",
  },
  {
    id: "5",
    question: "Este disponibil serviciul de livrare la adresă?",
    answer:
      "Da, oferăm serviciu de livrare în interiorul municipiului Chișinău. Pentru zonele situate în afara municipiului, pot aplica taxe suplimentare în funcție de distanță.",
  },
];
